from enum import Enum


class CRIME_TYPE(Enum):
    ROBBERY: "ROBBERY"
    MURDER = "MURDER"
    GANG_FORMATION = "RIDDLES"
    CATCHED_A_ROBIN = "CATCHED_A_ROBIN"
    CARRYING_RIDDLES = "CARRYING_RIDDLES"